using System;
using System.IO;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Spemcs.Agent.Core.Network;
using Xunit;

namespace Spemcs.Agent.Tests;

public sealed class PolicyDistributionTests : IDisposable
{
    private readonly string _tempDbPath;
    private readonly SqliteRollbackJournal _journal;
    private readonly TrustedKeyStore _keyStore;
    private readonly MockManagementConnectivityVerifier _connectivity;
    private readonly PolicyReceiver _receiver;

    // Cross-language test fixture generated by Python backend M2 signer
    private const string PythonPublicKeyPem = @"-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzJ6JteFg33KWaPABNb3/
f0jwRyJJL1jcwxMemlyUfMrH1W/rczxVw2dCJ0ou318qPYBtTMumzuGmASlZnpMw
VgjTIdS6EMyxX2fhFHf8CyCw1DRuKARKEXBA44dCu/umKhYTLCDQQ20Z3G2ApPGL
1tP5qPhIAFIafu1duWa7BIYT+17TofFjN4Zb1rvwA60mmqIdjMXbZbONrqnMDIK7
m6GErjzhnJNoxXyuIKJ/A99dJHTLCRr/SG59p/UgKG+VBpwdfrPUFJlEOXbiYi3y
fqRMwZnP7hsEKQQT42YZ6W1A8ySqrcfPmw+3hQZiCBIP0wL0mF3I7G3XLIYEv5qJ
NwIDAQAB
-----END PUBLIC KEY-----
";

    private const string PythonRawJson = "{\"allowed_destinations\":[{\"domains\":[\"test.example.com\"],\"ip_ranges\":[\"192.168.1.0/24\"],\"name\":\"TestVendor\",\"tcp_ports\":[443],\"udp_ports\":[]}],\"exam_id\":\"11111111-2222-3333-4444-555555555555\",\"expires_at\":\"2030-01-01T00:00:00Z\",\"key_id\":\"dev-key-1\",\"management_server\":{\"ip_addresses\":[\"127.0.0.1\"],\"port\":8000},\"not_before\":\"2026-01-01T00:00:00Z\",\"policy_id\":\"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee\",\"schema_version\":\"1.0\",\"vendor_profile_id\":null,\"version\":1}";
    private const string PythonSignatureBase64 = "hSuzYgf7vtIpk8uE7HwtPlP3j/jd+Xi67HHEBVxnxE1t6DJ5qLzWIE92gcCVdyXUhkwpcNa/DjtPYfhU584F3C/MZGB9nxyPCxCEbVAQokhjndaGYhDbsKsmRLPm7d5MIRXcqgvWzYuyGEmJvcc7PIjVRb0OqqtQxMClALOaz4aW/Ht9DWTZr/YgGdOHEVRIpyyhByTs0+xNSKDKTX+8J4QUGj4Di093lzBN8hie7KIPL8WmwXtT1h5KO4ZpyTLekgL/70loJ11maEpd3vCnyAlHjJ0aUKMGj3vwQcq3gQ4WppBNQcLpO0ihQizZ7DfGXxPDO93HBpv0HUBNsfXsIQ==";
    private static readonly Guid PythonExamId = Guid.Parse("11111111-2222-3333-4444-555555555555");

    public PolicyDistributionTests()
    {
        _tempDbPath = Path.Combine(Path.GetTempPath(), $"spemcs_m5_test_{Guid.NewGuid():N}");
        Directory.CreateDirectory(_tempDbPath);
        _journal = new SqliteRollbackJournal(_tempDbPath);
        _keyStore = new TrustedKeyStore();
        _connectivity = new MockManagementConnectivityVerifier(shouldSucceed: true);
        _receiver = new PolicyReceiver(_keyStore, _journal, _connectivity);

        // Register the python dev public key
        _keyStore.RegisterPublicKeyPem("dev-key-1", PythonPublicKeyPem);
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_tempDbPath))
                Directory.Delete(_tempDbPath, true);
        }
        catch { }
    }

    // =========================================================================
    // 1. Cross-Language Cryptographic Tests (Section 20)
    // =========================================================================

    [Fact]
    public async Task CrossLanguage_PythonM2Signature_VerifiesSuccessfullyInCSharp()
    {
        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: PythonRawJson,
            SignatureBase64: PythonSignatureBase64
        );

        // Test with a time inside validity window [2026-01-01, 2030-01-01]
        var evalTime = new DateTimeOffset(2026, 9, 3, 12, 0, 0, TimeSpan.Zero);

        var result = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId, evalTime);

        Assert.Equal(PolicyAcceptanceStatus.Accepted, result.Status);
        Assert.NotNull(result.ValidatedPolicy);
        Assert.Equal(PythonExamId, result.ValidatedPolicy.ExamId);
        Assert.Equal(1, result.ValidatedPolicy.Version);
        Assert.Equal("1.0", result.ValidatedPolicy.SchemaVersion);
        Assert.Equal(1, _connectivity.CallCount);
    }

    [Fact]
    public async Task TamperedRawPolicyJson_FailsSignatureVerification()
    {
        // Alter 1 byte in the raw JSON payload
        var tamperedJson = PythonRawJson.Replace("192.168.1.0/24", "192.168.2.0/24");

        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: tamperedJson,
            SignatureBase64: PythonSignatureBase64
        );

        var evalTime = new DateTimeOffset(2026, 9, 3, 12, 0, 0, TimeSpan.Zero);
        var result = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId, evalTime);

        Assert.Equal(PolicyAcceptanceStatus.InvalidSignature, result.Status);
        Assert.Null(result.ValidatedPolicy);
    }

    [Fact]
    public async Task TamperedSignatureBase64_FailsSignatureVerification()
    {
        // Flip characters in signature
        var tamperedSig = "A" + PythonSignatureBase64.Substring(1);

        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: PythonRawJson,
            SignatureBase64: tamperedSig
        );

        var evalTime = new DateTimeOffset(2026, 9, 3, 12, 0, 0, TimeSpan.Zero);
        var result = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId, evalTime);

        Assert.Equal(PolicyAcceptanceStatus.InvalidSignature, result.Status);
    }

    [Fact]
    public async Task UnknownKeyId_FailsClosed()
    {
        var rawWithUnknownKey = PythonRawJson.Replace("\"key_id\":\"dev-key-1\"", "\"key_id\":\"unknown-key-99\"");

        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: rawWithUnknownKey,
            SignatureBase64: PythonSignatureBase64
        );

        var evalTime = new DateTimeOffset(2026, 9, 3, 12, 0, 0, TimeSpan.Zero);
        var result = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId, evalTime);

        Assert.Equal(PolicyAcceptanceStatus.UnknownKey, result.Status);
    }

    [Fact]
    public async Task WrongKey_FailsSignatureVerification()
    {
        // Replace dev-key-1 with a freshly generated unrelated RSA key
        using var unrelatedRsa = RSA.Create(2048);
        var customKeyStore = new TrustedKeyStore();
        customKeyStore.RegisterPublicKey("dev-key-1", unrelatedRsa);

        var customReceiver = new PolicyReceiver(customKeyStore, _journal, _connectivity);

        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: PythonRawJson,
            SignatureBase64: PythonSignatureBase64
        );

        var evalTime = new DateTimeOffset(2026, 9, 3, 12, 0, 0, TimeSpan.Zero);
        var result = await customReceiver.ProcessPolicyMessageAsync(msg, PythonExamId, evalTime);

        Assert.Equal(PolicyAcceptanceStatus.InvalidSignature, result.Status);
    }

    // =========================================================================
    // 2. Protocol Wire & Message Envelope Tests
    // =========================================================================

    [Fact]
    public async Task MalformedMessageType_IsRejected()
    {
        var msg = new SignedPolicyMessage(
            MessageType: "UNKNOWN_MESSAGE_TYPE",
            ProtocolVersion: 1,
            RawPolicyJson: PythonRawJson,
            SignatureBase64: PythonSignatureBase64
        );

        var result = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId);
        Assert.Equal(PolicyAcceptanceStatus.InvalidMessage, result.Status);
    }

    [Fact]
    public async Task UnsupportedProtocolVersion_IsRejected()
    {
        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 99,
            RawPolicyJson: PythonRawJson,
            SignatureBase64: PythonSignatureBase64
        );

        var result = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId);
        Assert.Equal(PolicyAcceptanceStatus.UnsupportedSchema, result.Status);
    }

    [Fact]
    public async Task MissingRawPolicyJson_IsRejected()
    {
        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: "",
            SignatureBase64: PythonSignatureBase64
        );

        var result = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId);
        Assert.Equal(PolicyAcceptanceStatus.MissingFields, result.Status);
    }

    // =========================================================================
    // 3. Strict Schema Validation (Option A)
    // =========================================================================

    [Fact]
    public async Task StrictSchema_ExtraTopLevelField_IsRejected()
    {
        // Injected unauthorized extra top-level field into policy JSON
        var jsonWithExtraField = PythonRawJson.Replace(
            "\"schema_version\":\"1.0\",",
            "\"schema_version\":\"1.0\",\"attacker_injected_field\":\"malicious\",");

        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: jsonWithExtraField,
            SignatureBase64: PythonSignatureBase64
        );

        var result = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId);
        Assert.Equal(PolicyAcceptanceStatus.PolicyInvalid, result.Status);
        Assert.Contains("Unexpected top-level property", result.Details);
    }

    // =========================================================================
    // 4. Temporal & Window Validation Tests
    // =========================================================================

    [Fact]
    public async Task PolicyNotYetValid_IsRejected()
    {
        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: PythonRawJson,
            SignatureBase64: PythonSignatureBase64
        );

        // Before 2026-01-01
        var beforeTime = new DateTimeOffset(2025, 12, 31, 23, 59, 59, TimeSpan.Zero);
        var result = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId, beforeTime);

        Assert.Equal(PolicyAcceptanceStatus.NotYetValid, result.Status);
    }

    [Fact]
    public async Task PolicyExpired_IsRejected()
    {
        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: PythonRawJson,
            SignatureBase64: PythonSignatureBase64
        );

        // At or after 2030-01-01
        var afterTime = new DateTimeOffset(2030, 1, 1, 0, 0, 0, TimeSpan.Zero);
        var result = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId, afterTime);

        Assert.Equal(PolicyAcceptanceStatus.Expired, result.Status);
    }

    // =========================================================================
    // 5. Exam Context Binding Tests
    // =========================================================================

    [Fact]
    public async Task WrongExamBinding_IsRejected()
    {
        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: PythonRawJson,
            SignatureBase64: PythonSignatureBase64
        );

        var differentExamId = Guid.NewGuid();
        var evalTime = new DateTimeOffset(2026, 9, 3, 12, 0, 0, TimeSpan.Zero);

        var result = await _receiver.ProcessPolicyMessageAsync(msg, differentExamId, evalTime);

        Assert.Equal(PolicyAcceptanceStatus.ExamMismatch, result.Status);
    }

    // =========================================================================
    // 6. Monotonic Version & Rollback Protection Tests
    // =========================================================================

    [Fact]
    public async Task MonotonicVersion_ReplayAndRollbackAreRejected()
    {
        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: PythonRawJson,
            SignatureBase64: PythonSignatureBase64
        );

        var evalTime = new DateTimeOffset(2026, 9, 3, 12, 0, 0, TimeSpan.Zero);

        // First attempt: Accepted (version 1)
        var firstResult = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId, evalTime);
        Assert.Equal(PolicyAcceptanceStatus.Accepted, firstResult.Status);

        // Second attempt with same version 1: Rejected as replay
        var replayResult = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId, evalTime);
        Assert.Equal(PolicyAcceptanceStatus.VersionReplay, replayResult.Status);

        // Version state in new instance of journal survives
        var newJournal = new SqliteRollbackJournal(_tempDbPath);
        Assert.Equal(1, newJournal.GetHighestPolicyVersion(PythonExamId));
    }

    // =========================================================================
    // 7. Management Connectivity Verification Tests
    // =========================================================================

    [Fact]
    public async Task UnreachableManagementServer_RejectsPolicy()
    {
        var unreachableConnectivity = new MockManagementConnectivityVerifier(shouldSucceed: false);
        var receiver = new PolicyReceiver(_keyStore, _journal, unreachableConnectivity);

        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: PythonRawJson,
            SignatureBase64: PythonSignatureBase64
        );

        var evalTime = new DateTimeOffset(2026, 9, 3, 12, 0, 0, TimeSpan.Zero);
        var result = await receiver.ProcessPolicyMessageAsync(msg, PythonExamId, evalTime);

        Assert.Equal(PolicyAcceptanceStatus.ManagementUnreachable, result.Status);
    }

    // =========================================================================
    // 8. Firewall Invariance / Non-Interference (Section 18)
    // =========================================================================

    [Fact]
    public async Task PolicyReceiver_NeverTouchesFirewall()
    {
        var mockFirewall = new MockFirewallAdapter();
        var initialBaseline = mockFirewall.GetBaseline();

        var msg = new SignedPolicyMessage(
            MessageType: "SIGNED_NETWORK_POLICY",
            ProtocolVersion: 1,
            RawPolicyJson: PythonRawJson,
            SignatureBase64: PythonSignatureBase64
        );

        var evalTime = new DateTimeOffset(2026, 9, 3, 12, 0, 0, TimeSpan.Zero);
        var result = await _receiver.ProcessPolicyMessageAsync(msg, PythonExamId, evalTime);

        Assert.Equal(PolicyAcceptanceStatus.Accepted, result.Status);

        // Verify that 0 rules were added to firewall and baseline default action is untouched!
        Assert.Empty(mockFirewall.Rules);
        var currentBaseline = mockFirewall.GetBaseline();
        Assert.Equal(initialBaseline.DomainDefaultOutbound, currentBaseline.DomainDefaultOutbound);
        Assert.Equal(initialBaseline.PrivateDefaultOutbound, currentBaseline.PrivateDefaultOutbound);
        Assert.Equal(initialBaseline.PublicDefaultOutbound, currentBaseline.PublicDefaultOutbound);
    }
}
