"""Event -> generated by the Agent's classifier during monitoring.
Several fields (device_name, ip_address, student_roll_number) are denormalized
directly onto the event so it stays self-contained even if the device's info
changes later, and so the monitoring pipeline doesn't need a join on every write."""

import enum
import uuid
from datetime import datetime

from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from .base import Base


class Classification(str, enum.Enum):
    """The three-way classifier output described in the architecture doc."""
    ALLOWED = "allowed"
    ESSENTIAL_PROTECTED = "essential_protected"
    UNAUTHORIZED = "unauthorized"


class Event(Base):
    __tablename__ = "events"

    event_id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id = Column(UUID(as_uuid=True), ForeignKey("exam_sessions.session_id"), nullable=True)
    device_id = Column(UUID(as_uuid=True), ForeignKey("devices.device_id"), nullable=False)

    # denormalized for fast writes / self-contained records
    device_name = Column(String, nullable=False)
    ip_address = Column(String, nullable=True)
    student_roll_number = Column(String, nullable=True)

    event_type = Column(String, nullable=False)
    timestamp = Column(DateTime, nullable=False)

    process_name = Column(String, nullable=True)
    pid = Column(Integer, nullable=True)
    executable_path = Column(String, nullable=True)

    classification = Column(String, nullable=False)
    reason = Column(String, nullable=True)
    resolution_status = Column(String, nullable=True)

    session = relationship("ExamSession", back_populates="events")
    device = relationship("Device", back_populates="events")
    alert = relationship("Alert", back_populates="event", uselist=False)

    __table_args__ = (
        Index("ix_events_session_id", "session_id"),
        Index("ix_events_timestamp", "timestamp"),
        Index("ix_events_event_type", "event_type"),
        Index("ix_events_device_id", "device_id"),
    )
