<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><EnableWindowsTargeting>true</EnableWindowsTargeting></PropertyGroup><ItemGroup><ProjectReference Include="..\Spemcs.Agent.Ipc\Spemcs.Agent.Ipc.csproj" /><ProjectReference Include="..\Spemcs.Agent.Core\Spemcs.Agent.Core.csproj" /></ItemGroup></Project>
